name: pih2e
version: 0.1.0.6
github: "erlnow/pih2e"
license: BSD3
author: "erlnow"
maintainer: "erlestau@gmail.com"
copyright: "(c) 2010-2020 Eduardo Ramon Lestau"

#extra-source-dirs:
#  - README.md
#  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/erlnow/pih2e#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - pih2e
      - hspec == 2.*
      - QuickCheck
    build-tools: hspec-discover
